# Generated by Django 5.0.6 on 2024-07-26 01:52

import autoslug.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('to_the_department', models.CharField(blank=True, choices=[('Support & Helpdesk Department', 'Support & Helpdesk Department'), ('Report & Feedback Department', 'Report & Feedback Department'), ('Customer Support Department', 'Customer Support Department'), ('Accounts Department', 'Accounts Department'), ('Share your Knowledge', 'Share your Knowledge')], max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('Subscription', models.CharField(blank=True, choices=[('Build Business Profile', 'Build Business Profile'), ('Free E-books & Updates', 'Free E-books & Updates'), ('Free Sessions & Newsletter', 'Free Sessions & Newsletter'), ('Seminar and WorkShop', 'Seminar and WorkShop'), ('1 Month Workshop on Computer Proficiency For Office', '1 Month Workshop on Computer Proficiency For Office'), ('3 Month Proffessional Computer Certification Course', '3 Month Proffessional Computer Certification Course'), ('Send me all Updates', 'Send me all Updates')], max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('institute', models.CharField(blank=True, choices=[('S.B.S. Govt. P.G. College, U.S.Nagar', 'S.B.S. Govt. P.G. College, U.S.Nagar'), ('Institute of Management and Technology, Bindhukhera', 'Institute of Management and Technology, Bindhukhera')], max_length=100, null=True)),
                ('course', models.CharField(blank=True, choices=[('B.Sc 1 sem', 'B.Sc 1 sem'), ('B.Sc 2 year', 'B.Sc 2 year'), ('B.Sc 3 year', 'B.Sc 3 year'), ('B.Com 1 sem', 'B.Com 1 sem'), ('B.Com 2 year', 'B.Com 2 year'), ('B.Com 3 year', 'B.Com 3 year'), ('B.A 1 sem', 'B.A 1 sem'), ('B.A 2 year', 'B.A 2 year'), ('B.A 3 year', 'B.A 3 year'), ('B.B.A 1 sem', 'B.B.A 1 sem'), ('B.B.A 3 sem', 'B.B.A 3 sem'), ('B.B.A 5 sem', 'B.B.A 5 sem'), ('M.Sc 1 year', 'M.Sc 1 year'), ('M.Sc 2 year', 'M.Sc 2 year'), ('M.Com 1 year', 'M.Com 1 year'), ('M.Com 2 year', 'M.Com 2 year'), ('M.A 1 year', 'M.A 1 year'), ('M.A 2 year', 'M.A 2 year')], max_length=100, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile', models.CharField(max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Think',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='doodle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooltip', models.CharField(max_length=100)),
                ('detail', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='uploads/doodle')),
                ('event', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='event')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.BigIntegerField(default='0')),
                ('moredetail', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
