# Generated by Django 5.0.6 on 2024-07-26 01:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='fileshare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('about', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.CharField(blank=True, choices=[('Junior Class', 'Junior Class'), ('10th Class', '10th Class'), ('11th Class', '11th Class'), ('12th Class', '12th Class'), ('B.Sc', 'B.Sc'), ('B.Com', 'B.Com'), ('B.A', 'B.A'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('B.Ed', 'B.Ed'), ('M.Ed', 'M.Ed'), ('M.Sc', 'M.Sc'), ('M.Com', 'M.Com'), ('M.A', 'M.A'), ('Additional Information', 'Additional Information')], max_length=25, null=True)),
                ('semester', models.CharField(blank=True, choices=[('Additional Information', 'Additional Information'), ('1 Semester', '1 Semester'), ('2 Semester', '2 Semester'), ('3 Semester', '3 Semester'), ('4 Semester', '4 Semester'), ('5 Semester', '5 Semester'), ('6 Semester', '6 Semester')], max_length=23, null=True)),
                ('subjects', models.CharField(blank=True, choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Zoology', 'Zoology'), ('Statistics', 'Statistics'), ('Maths', 'Maths'), ('English', 'English'), ('Hindi', 'Hindi'), ('Sanskrit', 'Sanskrit'), ('Sociology', 'Sociology'), ('Computer Science', 'Computer Science'), ('Sociology', 'Sociology')], max_length=25, null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('highlight', models.CharField(blank=True, max_length=500, null=True)),
                ('choose_file', models.FileField(blank=True, null=True, upload_to='')),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, default=None, related_name='filelike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(blank=True, null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filecomment', to='post.fileshare')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('about', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.CharField(blank=True, choices=[('Junior Class', 'Junior Class'), ('10th Class', '10th Class'), ('11th Class', '11th Class'), ('12th Class', '12th Class'), ('B.Sc', 'B.Sc'), ('B.Com', 'B.Com'), ('B.A', 'B.A'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('B.Ed', 'B.Ed'), ('M.Ed', 'M.Ed'), ('M.Sc', 'M.Sc'), ('M.Com', 'M.Com'), ('M.A', 'M.A'), ('Additional Information', 'Additional Information')], max_length=35, null=True)),
                ('semester', models.CharField(blank=True, choices=[('Additional Information', 'Additional Information'), ('1 Semester', '1 Semester'), ('2 Semester', '2 Semester'), ('3 Semester', '3 Semester'), ('4 Semester', '4 Semester'), ('5 Semester', '5 Semester'), ('6 Semester', '6 Semester')], max_length=25, null=True)),
                ('subjects', models.CharField(blank=True, choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Zoology', 'Zoology'), ('Statistics', 'Statistics'), ('Maths', 'Maths'), ('English', 'English'), ('Hindi', 'Hindi'), ('Sanskrit', 'Sanskrit'), ('Sociology', 'Sociology'), ('Computer Science', 'Computer Science'), ('Sociology', 'Sociology')], max_length=25, null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.FileField(blank=True, null=True, upload_to='media')),
                ('content', models.TextField(blank=True, null=True)),
                ('content_addition', models.TextField(blank=True, null=True)),
                ('highlight', models.CharField(blank=True, max_length=500, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('notelikes', models.ManyToManyField(blank=True, default=None, related_name='notelike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(blank=True, null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcomment', to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
