# Generated by Django 5.0.6 on 2024-07-26 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('standard', models.CharField(blank=True, choices=[('Class 6th', 'Class 6th'), ('Class 7th', 'Class 7th'), ('Class 8th', 'Class 8th'), ('Class 9th', 'Class 9th'), ('Class 10th', 'Class 10th'), ('Class 11th', 'Class 11th'), ('Class 12th', 'Class 12th'), ('Undergraduate', 'Undergraduate'), ('Post-Undergraduate', 'Post-Undergraduate'), ('Self Learner', 'Self Learner')], max_length=30, null=True)),
                ('academicbackground', models.CharField(blank=True, choices=[('Central Board of Secondary Education', 'Central Board of Secondary Education'), ('ICSE Board', 'ICSE Board'), ('State Board', 'State Board'), ('Outside of India', 'Outside of India'), ('Learning by Myself', 'Learning by Myself')], max_length=40, null=True)),
                ('school_name', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(blank=True, choices=[('Out side of India', 'Out side of India'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunanchal Pradesh'), ('Assam', 'Assam '), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Himanchal Pradesh', 'Himanchal Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerela', 'Kerela'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh '), ('Maharastra', 'Maharastra '), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', ' Odisha'), ('Punjab', ' Punjab'), ('Puducherry', 'Puducherry'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Naidu', 'Tamil Naidu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=100, null=True)),
                ('country', models.CharField(blank=True, choices=[('India', 'India'), ('Europe Continent', 'Europe Continent'), ('Africa Continent', 'Africa Continent'), ('Australia Continent', 'Australia Continent'), ('Asia Continent', 'Asia Continent'), ('North America Continent', 'North America Continent'), ('South America Continent', 'South America Continent')], max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, default='uploads/profile_pictures/default.png', null=True, upload_to='uploads/profile_pictures')),
                ('follower', models.ManyToManyField(blank=True, related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
